### ISSUE TITLE
Problem set 2, basic question 3 does not import seaborn

### ISSUE THREAD

**Issue by KaWest** [physics-chalmers/tif285#14]
Should be an import statement 
`import seaborn as sns` 
somewhere before the plotting function in Q3 is invoked. Otherwise you get a ModuleImportError.

Tested it and it works locally but unsure about your setup for problem set notebooks so no pull request this time. 👨‍💻

**Comment by cforssen** [comment]
Thanks. Issue moved to separate git repo for exercises. Will close this issue here.
