### ISSUE TITLE
numpy, GPy and tensorflow results in unresolvable dependencies 

### ISSUE THREAD

**Issue by KaWest** [physics-chalmers/tif285#17]
Heads-up that might be relevant for other students.

The following dependency conflict seems to have emerged after new numpy version was released [beginning of this year](https://github.com/numpy/numpy/releases?after=v1.20.0): 

GPy 1.10 requires numpy >= 1.20. When running numpy version 1.19.x (on Macbook, BigSur) you will crash GPy on load with the following error: 
`ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
`

Tensorflow, however, wont operate with numpy > 1.19. See issue in numpy repo for reference:
https://github.com/tensorflow/tensorflow/issues/47691

**Comment by KaWest** [comment]
Requiring GPy == 1.9.9 seems to do the trick.

**Comment by cforssen** [comment]
Thanks @KaWest.
However, I seem to have a working combination on my MacBook Pro and can run both GPy and tensorflow demo notebooks. My configuration is the following:
$ python
Python 3.7.10 | packaged by conda-forge | (default, Feb 19 2021, 15:59:12) 
[Clang 11.0.1 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> np.__version__
'1.20.3'
>>> import GPy
>>> GPy.__version__
'1.10.0'
>>> import tensorflow as tf
>>> tf.__version__
'2.6.0'

**Comment by KaWest** [comment]
Found this laying around. Closing to not clutter your repo. Issue has been resolved in later updates of TF
