### ISSUE TITLE
Difference between Problem set 2 and lecture/exercise

### ISSUE THREAD

**Issue by www42www** [physics-chalmers/tif285#3]
Hello!
I realize it's a bit late for this now, but I just noticed a discrepancy between the definitions of 
$\theta$ in *Problem set 2* and lecture *Assigning probabilities* and exercise *Bayesian parameter estimation*. Although the $\theta$ are different ([m,b] vs [b,m]), the `log_symmetric_prior(theta)` is still the same. The exercise seems to agree with the lecture, but the Problem set is different, resulting in different pdf's when used as is.

Kind regards
Wojciech Chrobak

**Comment by cforssen** [comment]
Hi Wojciech,

Thanks for spotting this. You are correct that one has to be attentive to figure out which parameter is which one when applying the pre-defined prior in this problem. I will try to be careful when grading this problem to see if someone did get the wrong result as a result of this confusion. 
Cheers,
Christian
