### ISSUE TITLE
Issue on page /content/LinearRegression/LinearRegression.html

### ISSUE THREAD

**Issue by KaWest** [physics-chalmers/tif285#7]
Small typo in matrix dimension notation : 
`It means that our design matrix is a $p\times n$` should be 
`It means that our design matrix is a $ n \times p$`

**Comment by cforssen** [comment]
Thank you!
Fixed in commit 7bd5b56880d7275e6a1033a9ae330a47931f1f03
https://github.com/physics-chalmers/tif285/commit/7bd5b56880d7275e6a1033a9ae330a47931f1f03
Will appear in the next build.
